### ISSUE TITLE
Override `Pomodoro.whyNotDelete` 

### ISSUE THREAD

**Issue by JStanley19** [dewv/githubPomodoroApp#10]
```javascript
whyNotDelete() {
    return ["That operation is not supported."];
}
```

**Comment by omgordon** [comment]
@JStanley19 Is there any additional documentation on what needs to be done for this issue? I'm not familiar with our pomodoro system so I may be missing something obvious

**Comment by omgordon** [comment]
*accidentally hit 'close and comment' instead of 'comment', issue reopened

**Comment by JStanley19** [comment]
> @JStanley19 Is there any additional documentation on what needs to be done for this issue? I'm not familiar with our pomodoro system so I may be missing something obvious

@omgordon Not necessarily, the "operation is not supported" so it's pretty simple. I'll try to point you to more info if you can't.

**Comment by omgordon** [comment]
I've been trying to find an example to work off of, but am not sure entirely what to look for. Is there an example you can point me to or some sort of guidelines for what needs to be done? I'm struggling to suss out what I need to do

**Comment by JStanley19** [comment]
> I've been trying to find an example to work off of, but am not sure entirely what to look for. Is there an example you can point me to or some sort of guidelines for what needs to be done? I'm struggling to suss out what I need to do edit: they need to move the comment and close button >:(

It is merely a class in the Pomodoro service code, under the pomodoro class.
`
    // TODO figure out which operations are supported
    // /** @override */
    // static whyNotList(context, callback) {
    //     callback(["Because I said so.", "Also, I hate you."]);
    // }
}`

It goes within this area

**Comment by omgordon** [comment]
That might be why I'm confused, I don't see any files in the services for pomodoro, which is probably why I have no clue what file I'm supposed to be editing. the services folder is empty and a file search on c9 didn't find text matching 
```// TODO figure out which operations are supported // /** @override */ // static whyNotList(context, callback) { // callback(["Because I said so.", "Also, I hate you."]); // } }```

**Comment by JStanley19** [comment]
> That might be why I'm confused, I don't see any files in the services for pomodoro, which is probably why I have no clue what file I'm supposed to be editing. the services folder is empty and a file search on c9 didn't find text matching
> `// TODO figure out which operations are supported // /** @override */ // static whyNotList(context, callback) { // callback(["Because I said so.", "Also, I hate you."]); // } }`

Ah, yes. My recent pull request to master is failing. The code is currently stuck on the pomodoroModel branch.

**Comment by omgordon** [comment]
ah that makes sense, I'll take a look at that, thanks!

**Comment by omgordon** [comment]
Okay, it has been added, although I put it outside of the comments which I assumed was just as an example template. Should I try to make the pull request for master or for your branch? I had to clone your branch with pomodoro.js to work but you mentioned it was failing to merge into master itself so I'm not sure that benefits anyone to do

**Comment by JStanley19** [comment]
> Okay, it has been added, although I put it outside of the comments which I assumed was just as an example template. Should I try to make the pull request for master or for your branch? I had to clone your branch with pomodoro.js to work but you mentioned it was failing to merge into master itself so I'm not sure that benefits anyone to do

Do it just for the sub branch. There are issues that need fixed before a merge into master can be made,
